print('Welcome to the Band NAme Generator.')
print("What's the name of the city you grew up in?")
city = input()
print("What's your pet's name?")
pet = input()
print(f"Your band name could be {city} {pet}.")