word_list = [
    "apple", "banana", "orange", "grape", "melon", "kiwi", "mango", "peach", "plum", "lemon",
    "avocado", "blueberry", "raspberry", "strawberry", "watermelon", "cherry", "coconut", "fig", "guava", "papaya",
    "car", "train", "bus", "bicycle", "scooter", "skateboard", "truck", "airplane", "helicopter", "boat",
    "cat", "dog", "mouse", "elephant", "giraffe", "zebra", "lion", "tiger", "bear", "monkey",
    "house", "castle", "palace", "cabin", "mansion", "hut", "apartment", "bungalow", "villa", "dorm",
    "book", "novel", "magazine", "newspaper", "pamphlet", "manual", "dictionary", "encyclopedia", "journal", "guide",
    "table", "chair", "couch", "sofa", "desk", "dresser", "cabinet", "shelf", "bench", "stool",
    "red", "blue", "green", "yellow", "purple", "orange", "white", "black", "gray", "pink",
    "python", "java", "ruby", "perl", "swift", "kotlin", "scala", "go", "dart", "rust",
    "school", "college", "university", "library", "classroom", "dormitory", "cafeteria", "gymnasium", "auditorium", "laboratory",
    "pencil", "pen", "eraser", "ruler", "notebook", "marker", "sharpener", "backpack", "stapler", "paper",
    "sun", "moon", "planet", "star", "galaxy", "comet", "asteroid", "nebula", "meteor", "eclipse",
    "cold", "hot", "warm", "cool", "freezing", "boiling", "breezy", "stormy", "rainy", "snowy",
    "happy", "sad", "angry", "excited", "nervous", "scared", "bored", "calm", "proud", "shy",
    "dance", "sing", "draw", "paint", "write", "read", "run", "jump", "swim", "climb",
    "mountain", "valley", "river", "ocean", "desert", "forest", "island", "canyon", "waterfall", "volcano",
    "clock", "watch", "calendar", "alarm", "timer", "hourglass", "sundial", "stopwatch", "bell", "whistle",
    "doctor", "nurse", "teacher", "engineer", "artist", "scientist", "lawyer", "firefighter", "police", "chef",
    "bread", "butter", "cheese", "milk", "yogurt", "cream", "egg", "bacon", "ham", "toast",
    "football", "basketball", "baseball", "soccer", "tennis", "golf", "hockey", "cricket", "rugby", "volleyball",
    "rainbow", "cloud", "thunder", "lightning", "fog", "mist", "hail", "breeze", "gust", "storm",
    "gold", "silver", "bronze", "copper", "platinum", "diamond", "emerald", "ruby", "sapphire", "pearl",
    "shirt", "pants", "jacket", "coat", "hat", "scarf", "gloves", "socks", "shoes", "boots",
    "robot", "computer", "laptop", "tablet", "phone", "screen", "keyboard", "mouse", "printer", "camera",
    "river", "lake", "pond", "creek", "stream", "bay", "gulf", "harbor", "lagoon", "reservoir",
    "castle", "bridge", "tower", "lighthouse", "fort", "church", "temple", 
]